# Journal Documents the retrieval of the sample data from refine.bio and archs4

### Original Author: Ling Thang - PATH GREU edited by Kewalin Samart

notebook contains scipt to retrive data for 
* Tuberculosis (TB)

In [2]:
import archs4py as a4
import numpy as np
import pandas as pd

In [ ]:
# downloads the latest version of the human counts file
# a4.download.counts("human", path = "GEO expression", type = "GENE_COUNTS", version = "latest") 
# also available on the ARCHS4 website : https://archs4.org/download

In [ ]:
file = "../data/human_gene_v2.5.h5"
a4.ls(file)

#### Helper Function

In [3]:
def split_and_clean_series_ids(series_list):
    """
    Split comma-separated series IDs and clean whitespace
    
    Parameters:
    series_list: List of strings that may contain comma-separated values
    
    Returns:
    numpy.ndarray: Array of cleaned, individual series IDs
    """
    split_list = []
    for item in series_list:
        split_list.extend([x.strip() for x in str(item).split(',')])
    
    return np.array(split_list)

**Mircroarrays data**

We queried the refine.bio database using the keywords “pulmonary tuberculosis,” “active tuberculosis,” and “MTB” to retrieve available gene expression datasets and their corresponding metadata. These datasets were originally deposited in the Gene Expression Omnibus (GEO) and were uniformly processed by [refine.bio](https://www.refine.bio/) up to June 2025. Data were downloaded according to the instructions provided on the refine.bio platform.

The datasets included in this study, along with detailed curation information, are listed in
`../data/labeling/TB_curationdoc.tsv.`

**RNAseq data**

Similarly, for RNA-seq data, we obtained uniformly processed gene expression data and associated metadata using the [archs4py](https://github.com/MaayanLab/archs4py) Python library with the same keywords: “pulmonary tuberculosis,” “active tuberculosis,” and “MTB.” Datasets available up to June 2025 were retrieved. Further details of the data retrieval process are provided in the code section below.

The datasets included in this study, together with detailed curation information, are listed in
`../data/labeling/TB_curationdoc.tsv.`

In [ ]:
# get sample meta data based on search term
PTB_meta = a4.meta.meta(file, "pulmonary tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

# get sample meta data based on search term
activeTB_meta = a4.meta.meta(file, "active tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

# get sample meta data based on search term
MTB_meta = a4.meta.meta(file, "MTB", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

100%|██████████| 6/6 [00:03<00:00,  1.95it/s]
100%|██████████| 6/6 [00:02<00:00,  2.08it/s]
100%|██████████| 6/6 [00:02<00:00,  2.15it/s]
100%|██████████| 6/6 [00:02<00:00,  2.00it/s]

In [4]:
import pandas as pd
TB_meta = pd.concat([PTB_meta, activeTB_meta, MTB_meta], ignore_index=True)
TB_meta

,geo_accession,series_id,characteristics_ch1,extract_protocol_ch1,source_name_ch1,title
0,GSM2732743,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-1
1,GSM2732744,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-2
2,GSM4810280,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H1
3,GSM4810281,GSE158767,"METABOLIC ACTIVITY: LOW METABOLIC ACTIVITY,GEN...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE L1
4,GSM4810282,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H2
...,...,...,...,...,...,...
2405,GSM8087252,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB UNINFECTED, 48 HOURS, 4"
2406,GSM8087253,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 1"
2407,GSM8087254,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 2"
2408,GSM8087255,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 3"
2409,GSM8087256,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 4"

In [ ]:
MTB_meta2 = a4.meta.meta(file, "mycobacterium tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])
lung_TB = a4.meta.meta(file, "lung tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

lung_TB2 = a4.meta.meta(file, "lung TB", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

100%|██████████| 6/6 [00:02<00:00,  2.06it/s]
100%|██████████| 6/6 [00:02<00:00,  2.06it/s]
100%|██████████| 6/6 [00:02<00:00,  2.06it/s]

In [8]:
import pandas as pd
TB_meta_updated= pd.concat([PTB_meta, activeTB_meta, MTB_meta, MTB_meta2, lung_TB, lung_TB2], ignore_index=True)
TB_meta_updated

,geo_accession,series_id,characteristics_ch1,extract_protocol_ch1,source_name_ch1,title
0,GSM2732743,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-1
1,GSM2732744,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-2
2,GSM4810280,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H1
3,GSM4810281,GSE158767,"METABOLIC ACTIVITY: LOW METABOLIC ACTIVITY,GEN...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE L1
4,GSM4810282,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H2
...,...,...,...,...,...,...
2579,GSM5573721,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),18P_TTNPB
2580,GSM5573723,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_ATRA
2581,GSM5573724,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_DMSO
2582,GSM5573725,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_EC23
2583,GSM5573726,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_TTNPB

In [11]:
TB_meta_list_updated = TB_meta_updated["series_id"].unique().tolist()
print(TB_meta_updated['series_id'].unique())
print(len(TB_meta_updated['series_id'].unique()))

['GSE102272' 'GSE158767' 'GSE190024' 'GSE84076' 'GSE94907' 'GSE148171'
 'GSE152218' 'GSE198557' 'GSE64179,GSE64183' 'GSE64182,GSE64183'
 'GSE100897' 'GSE102677,GSE102678' 'GSE103147' 'GSE107646' 'GSE112482'
 'GSE112483' 'GSE116405,GSE116412' 'GSE131415' 'GSE132048' 'GSE132283'
 'GSE138398' 'GSE141656' 'GSE143627' 'GSE148731' 'GSE162725' 'GSE164287'
 'GSE165708,GSE165709' 'GSE174566' 'GSE180480' 'GSE193777' 'GSE194017'
 'GSE199403' 'GSE207214' 'GSE211974,GSE211977' 'GSE216503' 'GSE223863'
 'GSE236154' 'GSE236156' 'GSE256184' 'GSE110564' 'GSE121049' 'GSE131590'
 'GSE143731' 'GSE183912']
44

In [12]:
TB_meta_split = []
for item in TB_meta_list_updated:
    TB_meta_split.extend([x.strip() for x in item.split(',')])
TB_meta_split = np.array(TB_meta_split)

print(TB_meta_split)
print(len(TB_meta_split))

# print the dup
print("Duplicates in TB_meta_split:")
duplicates = set(x for x in TB_meta_split if TB_meta_split.tolist().count(x) > 1)
print(duplicates)

# remove duplicates
TB_meta_split = np.unique(TB_meta_split)
print("After removing duplicates:")
print(len(TB_meta_split))

['GSE102272' 'GSE158767' 'GSE190024' 'GSE84076' 'GSE94907' 'GSE148171'
 'GSE152218' 'GSE198557' 'GSE64179' 'GSE64183' 'GSE64182' 'GSE64183'
 'GSE100897' 'GSE102677' 'GSE102678' 'GSE103147' 'GSE107646' 'GSE112482'
 'GSE112483' 'GSE116405' 'GSE116412' 'GSE131415' 'GSE132048' 'GSE132283'
 'GSE138398' 'GSE141656' 'GSE143627' 'GSE148731' 'GSE162725' 'GSE164287'
 'GSE165708' 'GSE165709' 'GSE174566' 'GSE180480' 'GSE193777' 'GSE194017'
 'GSE199403' 'GSE207214' 'GSE211974' 'GSE211977' 'GSE216503' 'GSE223863'
 'GSE236154' 'GSE236156' 'GSE256184' 'GSE110564' 'GSE121049' 'GSE131590'
 'GSE143731' 'GSE183912']
50
Duplicates in TB_meta_split:
{'GSE64183'}
After removing duplicates:
49